Repository HalfGallonTeam/WithCon_BE, pull requests merged in 2024-02, with the labels that each got.

#32 [feat] 채팅 태그 기능 추가
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomRequest.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/entity/ChatRoom.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/tag/controller/TagController.java
  src/main/java/com/halfgallon/withcon/domain/tag/dto/TagCountDto.java
  src/main/java/com/halfgallon/withcon/domain/tag/dto/TagDto.java
  src/main/java/com/halfgallon/withcon/domain/tag/entity/Tag.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/CustomTagRepository.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/TagRepository.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/impl/CustomTagRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/tag/service/TagService.java
  src/main/java/com/halfgallon/withcon/domain/tag/service/TagServiceImpl.java
  src/test/http/chatRoom.http
  src/test/http/tag.http
  src/test/java/com/halfgallon/withcon/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/tag/repository/TagRepositoryTest.java
Labels: ✅ Test, ✨ feature, 🔥 backend

#34 [feat] 토큰 검증 및 액세스 토큰 재발급 API 추가
  src/main/java/com/halfgallon/withcon/domain/auth/constant/AuthConstant.java
  src/main/java/com/halfgallon/withcon/domain/auth/controller/AuthController.java
  src/main/java/com/halfgallon/withcon/domain/auth/manager/JwtManager.java
  src/main/java/com/halfgallon/withcon/domain/auth/repository/AccessTokenRepository.java
  src/main/java/com/halfgallon/withcon/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/config/SecurityConfig.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/handler/LoginSuccessHandler.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/service/CustomUserDetailsService.java
  src/main/java/com/halfgallon/withcon/domain/auth/service/AuthService.java
  src/main/java/com/halfgallon/withcon/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatMessageServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/halfgallon/withcon/global/exception/ErrorCode.java
  src/test/java/com/halfgallon/withcon/domain/auth/api/LoginTest.java
  src/test/java/com/halfgallon/withcon/domain/auth/api/LogoutTest.java
  src/test/java/com/halfgallon/withcon/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/auth/security/filter/JwtAuthenticationFilterTest.java
  src/test/java/com/halfgallon/withcon/domain/auth/service/AuthServiceImplTest.java
Labels: ✅ Test, ✨ feature, 🔥 backend

#41 [feat] 태그 이름 검색 시 태그 갯수가 많은 순으로 조회
  src/main/java/com/halfgallon/withcon/domain/tag/controller/TagController.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/CustomTagRepository.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/impl/CustomTagRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/tag/service/TagService.java
  src/main/java/com/halfgallon/withcon/domain/tag/service/TagServiceImpl.java
  src/test/http/tag.http
  src/test/java/com/halfgallon/withcon/domain/tag/repository/TagRepositoryTest.java
Labels: ✨ feature, 🔥 backend

#46 [feat] RabbitMQ 도커파일 생성
  docker/docker-compose.yml
  docker/rabbitMQ/Dockerfile
Labels: ✨ feature, 🔥 backend, ✨Infra

#48 [refactor] 채팅서비스 코드 리팩토링 진행
  src/main/java/com/halfgallon/withcon/domain/chat/repository/ChatParticipantRepository.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatParticipantServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/test/http/chatRoom.http
  src/test/http/tag.http
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatParticipantServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/tag/repository/TagRepositoryTest.java
Labels: ✅ Test, 🔨 Refactor, 🔥 backend

#51 [refactor] 채팅서비스 CustomUserDetails 적용 및 ErrorCode 반환값 변경
  src/main/java/com/halfgallon/withcon/domain/auth/security/handler/LoginFailureHandler.java
  src/main/java/com/halfgallon/withcon/domain/chat/controller/ChatParticipantController.java
  src/main/java/com/halfgallon/withcon/domain/chat/controller/ChatRoomController.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomRequest.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/ChatParticipantService.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/ChatRoomService.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatParticipantServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/halfgallon/withcon/global/exception/CustomException.java
  src/main/java/com/halfgallon/withcon/global/exception/ErrorCode.java
  src/main/java/com/halfgallon/withcon/global/exception/ErrorResponse.java
  src/main/java/com/halfgallon/withcon/global/exception/GlobalExceptionHandler.java
  src/test/http/auth.http
  src/test/http/chatParticipant.http
  src/test/http/chatRoom.http
  src/test/java/com/halfgallon/withcon/domain/auth/api/LoginTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatParticipantServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImplTest.java
Labels: ✅ Test, 🔨 Refactor, 🔥 backend

#53 [feat] 채팅 메시지 저장 및 무한스크롤 구현
  src/main/java/com/halfgallon/withcon/domain/chat/constant/ChattingConstant.java
  src/main/java/com/halfgallon/withcon/domain/chat/controller/ChatMessageController.java
  src/main/java/com/halfgallon/withcon/domain/chat/controller/ChatRoomController.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatMessageRequest.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomEnterResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/entity/ChatMessage.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/CustomChatMessageRepository.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/impl/CustomChatMessageRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/ChatMessageService.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/ChatRoomService.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatMessageServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/test/http/auth.http
  src/test/http/chatRoom.http
  src/test/java/com/halfgallon/withcon/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/repository/ChatMessageRepositoryTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/tag/repository/TagRepositoryTest.java
Labels: ✅ Test, ✨ feature, 🔥 backend

#56 [feat] 방장 강퇴 기능 구현
  src/main/java/com/halfgallon/withcon/domain/chat/controller/ChatMessageController.java
  src/main/java/com/halfgallon/withcon/domain/chat/controller/ChatRoomController.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/ChatMessageService.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/ChatRoomService.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatMessageServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/test/http/chatRoom.http
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImplTest.java
Labels: ✅ Test, ✨ feature, 🔥 backend

#59 [feat] 소셜 로그인 기능 추가
  build.gradle
  src/main/java/com/halfgallon/withcon/domain/auth/client/OAuth2Client.java
  src/main/java/com/halfgallon/withcon/domain/auth/client/OAuth2UserInfo.java
  src/main/java/com/halfgallon/withcon/domain/auth/client/kakao/KakaoLoginClient.java
  src/main/java/com/halfgallon/withcon/domain/auth/client/kakao/KakaoUserInfoClient.java
  src/main/java/com/halfgallon/withcon/domain/auth/client/kakao/dto/request/KaKaoAccessTokenRequest.java
  src/main/java/com/halfgallon/withcon/domain/auth/client/kakao/dto/response/KakaoAccessTokenResponse.java
  src/main/java/com/halfgallon/withcon/domain/auth/client/kakao/dto/response/KakaoUserInfoResponse.java
  src/main/java/com/halfgallon/withcon/domain/auth/client/kakao/service/KakaoOAuth2Service.java
  src/main/java/com/halfgallon/withcon/domain/auth/client/naver/NaverLoginClient.java
  src/main/java/com/halfgallon/withcon/domain/auth/client/naver/NaverUserInfoClient.java
  src/main/java/com/halfgallon/withcon/domain/auth/client/naver/dto/request/NaverAccessTokenRequest.java
  src/main/java/com/halfgallon/withcon/domain/auth/client/naver/dto/response/NaverAccessTokenResponse.java
  src/main/java/com/halfgallon/withcon/domain/auth/client/naver/dto/response/NaverUserInfoResponse.java
  src/main/java/com/halfgallon/withcon/domain/auth/client/naver/service/NaverOAuth2Service.java
  src/main/java/com/halfgallon/withcon/domain/auth/controller/AuthController.java
  src/main/java/com/halfgallon/withcon/domain/auth/dto/request/AuthJoinRequest.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/config/SecurityConfig.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/filter/OAuth2LoginFilter.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/provider/OAuth2LoginProvider.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/token/CustomOAuth2Token.java
  src/main/java/com/halfgallon/withcon/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/member/dto/MemberDto.java
  src/main/java/com/halfgallon/withcon/domain/member/entity/Member.java
  src/main/java/com/halfgallon/withcon/domain/member/repository/MemberRepository.java
  src/main/java/com/halfgallon/withcon/global/config/OpenFeignConfig.java
  src/main/java/com/halfgallon/withcon/global/exception/ErrorCode.java
  src/test/java/com/halfgallon/withcon/domain/auth/api/LoginTest.java
  src/test/java/com/halfgallon/withcon/domain/auth/api/LogoutTest.java
  src/test/java/com/halfgallon/withcon/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/auth/service/AuthServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatParticipantServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/member/repository/MemberRepositoryTest.java
Labels: ✨ feature, 🔥 backend

#60 [refactor] Auth와 Member 단순 수정
  src/main/java/com/halfgallon/withcon/domain/auth/security/handler/LoginFailureHandler.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/handler/LoginSuccessHandler.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/halfgallon/withcon/domain/member/entity/Member.java
  src/main/java/com/halfgallon/withcon/global/exception/ErrorCode.java
  src/test/http/auth.http
Labels: 🐞 bug, 🔥 backend

#65 [chore] 배포 설정 파일 구현
  docker/api/Dockerfile
  docker/docker-compose.yml
  docker/jenkins/Dockerfile
  docker/nginx.conf
  src/main/resources/application.yml
Labels: ⚙ chore, 🔥 backend, ✨Infra

#66 [feat] Memer CRUD 기능 추가
  src/main/java/com/halfgallon/withcon/domain/auth/security/config/SecurityConfig.java
  src/main/java/com/halfgallon/withcon/domain/member/controller/MemberController.java
  src/main/java/com/halfgallon/withcon/domain/member/dto/request/UpdateMemberRequest.java
  src/main/java/com/halfgallon/withcon/domain/member/dto/response/MemberMyInfoResponse.java
  src/main/java/com/halfgallon/withcon/domain/member/entity/Member.java
  src/main/java/com/halfgallon/withcon/domain/member/service/MemberService.java
  src/main/java/com/halfgallon/withcon/domain/member/service/impl/MemberServiceImpl.java
  src/test/java/com/halfgallon/withcon/domain/chat/repository/ChatMessageRepositoryTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatParticipantServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/member/controller/MemberControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/member/service/impl/MemberServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/tag/repository/TagRepositoryTest.java
Labels: ✅ Test, ✨ feature, 🔥 backend

#69 [refactor] 채팅방 서비스 리팩토링
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatParticipantDto.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomEnterResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/member/dto/MemberDto.java
Labels: 🔨 Refactor, 🔥 backend

#70 [fix] 배포 에러 수정
  docker/docker-compose.yml
  src/main/java/com/halfgallon/withcon/domain/chat/config/RabbitConfig.java
  src/main/java/com/halfgallon/withcon/domain/chat/config/WebSocketConfig.java
Labels: 🐞 bug, ⚙ chore, 🔥 backend, ✨Infra

#73 [feat] 채팅방 공연 서비스 추가 및 ddl 파일 생성
  sql/performance.sql
  sql/performanceDetail.sql
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomRequest.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/entity/ChatRoom.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/performance/constant/Genre.java
  src/main/java/com/halfgallon/withcon/domain/performance/constant/Status.java
  src/main/java/com/halfgallon/withcon/domain/performance/entitiy/PerformanceDetail.java
  src/test/http/chatRoom.http
Labels: ✅ Test, ✨ feature, 🔥 backend

#77 [test] 채팅 서비스 테스트 코드 작성
  src/test/java/com/halfgallon/withcon/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatParticipantServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/tag/repository/TagRepositoryTest.java
Labels: ✅ Test, 🔥 backend

#67 [feat] 검색어 자동완성 기능 구현
  build.gradle
  docker/docker-compose.yml
  docker/elastic_search/Dockerfile
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/tag/controller/TagController.java
  src/main/java/com/halfgallon/withcon/domain/tag/dto/TagDto.java
  src/main/java/com/halfgallon/withcon/domain/tag/dto/TagSearchDto.java
  src/main/java/com/halfgallon/withcon/domain/tag/entity/TagSearch.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/CustomTagSearchRepository.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/TagRepository.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/TagSearchRepository.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/impl/CustomTagSearchRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/tag/service/TagService.java
  src/main/java/com/halfgallon/withcon/domain/tag/service/TagServiceImpl.java
  src/main/java/com/halfgallon/withcon/global/config/ElasticSearchConfig.java
  src/main/resources/static/elastic/elastic-settings.json
  src/main/resources/static/elastic/tag-mappings.json
Labels: ⚙ chore, ✨ feature, 🔥 backend

#78 [refactor] Auth 단순 수정
  src/main/java/com/halfgallon/withcon/domain/auth/controller/AuthController.java
  src/main/java/com/halfgallon/withcon/domain/auth/manager/JwtManager.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/config/SecurityConfig.java
  src/main/java/com/halfgallon/withcon/global/exception/ErrorCode.java
  src/test/http/auth.http
Labels: 🔨 Refactor, 🔥 backend

#83 chore: nginx 설정 추가
  docker/docker-compose.yml
Labels: ⚙ chore, 🔥 backend, ✨Infra

#79 [feat] 회원가입 시 username, phoneNumber 중복체크 API 추가
  src/main/java/com/halfgallon/withcon/domain/auth/controller/AuthController.java
  src/main/java/com/halfgallon/withcon/domain/auth/service/AuthService.java
  src/main/java/com/halfgallon/withcon/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/member/repository/MemberRepository.java
  src/main/java/com/halfgallon/withcon/global/exception/ErrorCode.java
  src/test/java/com/halfgallon/withcon/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/auth/service/AuthServiceImplTest.java
Labels: ✅ Test, ✨ feature, 🔥 backend

#84 [feat] 회원 프로필 사진 업로드 추가
  build.gradle
  src/main/java/com/halfgallon/withcon/domain/member/controller/MemberController.java
  src/main/java/com/halfgallon/withcon/domain/member/entity/Member.java
  src/main/java/com/halfgallon/withcon/domain/member/service/MemberService.java
  src/main/java/com/halfgallon/withcon/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/halfgallon/withcon/global/storage/service/StorageService.java
  src/main/java/com/halfgallon/withcon/global/storage/service/impl/AwsS3Service.java
  src/test/java/com/halfgallon/withcon/domain/member/controller/MemberControllerTest.java
Labels: ✅ Test, ✨ feature, 🔥 backend

#76 [feat] 공연 검색 기능 구현
  src/main/java/com/halfgallon/withcon/domain/performance/controller/PerformanceController.java
  src/main/java/com/halfgallon/withcon/domain/performance/dto/request/PerformanceRequest.java
  src/main/java/com/halfgallon/withcon/domain/performance/dto/response/PerformanceResponse.java
  src/main/java/com/halfgallon/withcon/domain/performance/entitiy/Performance.java
  src/main/java/com/halfgallon/withcon/domain/performance/repository/CustomPerformanceRepository.java
  src/main/java/com/halfgallon/withcon/domain/performance/repository/PerformanceRepository.java
  src/main/java/com/halfgallon/withcon/domain/performance/repository/impl/CustomPerformanceRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/performance/service/PerformanceService.java
  src/main/java/com/halfgallon/withcon/domain/performance/service/impl/PerformanceServiceImpl.java
  src/test/java/com/halfgallon/withcon/domain/performance/controller/PerformanceControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/performance/service/impl/PerformanceServiceImplTest.java
Labels: ✨ feature, 🔥 backend

#90 [feat] 채팅방 참여자 유저프로필 정보 반환
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatParticipantDto.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/test/java/com/halfgallon/withcon/domain/performance/controller/PerformanceControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/performance/service/impl/PerformanceServiceImplTest.java
Labels: ✨ feature, 🔥 backend

#88 [refactor] 채팅방 방장 Response 변경
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatParticipantDto.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomEnterResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomRequest.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/entity/ChatParticipant.java
  src/main/java/com/halfgallon/withcon/domain/chat/entity/ChatRoom.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/CustomChatParticipantRepository.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/impl/CustomChatParticipantRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/test/http/auth.http
  src/test/http/chatRoom.http
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImplTest.java
Labels: ✅ Test, 🔨 Refactor, 🔥 backend

#93 [refactor] 채팅방 입장 Response 변경
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatParticipantDto.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomEnterResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
Labels: 🔨 Refactor, 🔥 backend

#91 [Feat] 공연 찜 기능
  src/main/java/com/halfgallon/withcon/domain/member/entity/Member.java
  src/main/java/com/halfgallon/withcon/domain/notification/dto/ChatRoomNotificationRequest.java
  src/main/java/com/halfgallon/withcon/domain/notification/dto/RedisChannelRequest.java
  src/main/java/com/halfgallon/withcon/domain/notification/dto/VisibleRequest.java
  src/main/java/com/halfgallon/withcon/domain/performance/controller/PerformanceLikeController.java
  src/main/java/com/halfgallon/withcon/domain/performance/dto/response/MainPagePerformanceResponse.java
  src/main/java/com/halfgallon/withcon/domain/performance/entitiy/Performance.java
  src/main/java/com/halfgallon/withcon/domain/performance/entitiy/PerformanceLike.java
  src/main/java/com/halfgallon/withcon/domain/performance/repository/CustomPerformanceRepository.java
  src/main/java/com/halfgallon/withcon/domain/performance/repository/PerformanceLikeRepository.java
  src/main/java/com/halfgallon/withcon/domain/performance/repository/PerformanceRepository.java
  src/main/java/com/halfgallon/withcon/domain/performance/repository/impl/CustomPerformanceRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/performance/service/PerformanceLikeService.java
  src/main/java/com/halfgallon/withcon/domain/performance/service/impl/PerformanceLikeServiceImpl.java
  src/main/java/com/halfgallon/withcon/global/exception/ErrorCode.java
  src/test/java/com/halfgallon/withcon/domain/performance/service/impl/PerformanceLikeServiceImplTest.java
Labels: ✨ feature, 🔥 backend

#94 [refactor] 내 정보 조회 필드 추가
  src/main/java/com/halfgallon/withcon/domain/member/dto/response/MemberMyInfoResponse.java
  src/test/java/com/halfgallon/withcon/domain/member/service/impl/MemberServiceImplTest.java
Labels: 🔨 Refactor, 🔥 backend

#96 [refactor] 채팅 메시지 리팩토링
  src/main/java/com/halfgallon/withcon/domain/chat/controller/ChatMessageController.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/halfgallon/withcon/domain/chat/entity/ChatMessage.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatMessageServiceImpl.java
Labels: 🔨 Refactor, 🔥 backend

#99 [fix] 필터 내 예외처리를 위한 ExceptionHandlingFilter 추가
  src/main/java/com/halfgallon/withcon/domain/auth/security/config/SecurityConfig.java
  src/main/java/com/halfgallon/withcon/domain/auth/security/filter/ExceptionHandlingFilter.java
Labels: 🐞 bug, ✅ Test, 🔥 backend

#100 [fix] 중복 체크 API
  src/main/java/com/halfgallon/withcon/domain/auth/controller/AuthController.java
  src/main/java/com/halfgallon/withcon/domain/auth/dto/request/DuplicationCheckRequest.java
Labels: 🐞 bug, ✅ Test, 🔥 backend

#101 [refactor] 공연 검색 기능 리팩토링
  src/main/java/com/halfgallon/withcon/domain/performance/constant/Genre.java
  src/main/java/com/halfgallon/withcon/domain/performance/controller/PerformanceController.java
  src/main/java/com/halfgallon/withcon/domain/performance/entitiy/Performance.java
  src/main/java/com/halfgallon/withcon/domain/performance/repository/CustomPerformanceRepository.java
  src/main/java/com/halfgallon/withcon/domain/performance/repository/impl/CustomPerformanceRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/performance/service/PerformanceService.java
  src/main/java/com/halfgallon/withcon/domain/performance/service/impl/PerformanceServiceImpl.java
  src/main/java/com/halfgallon/withcon/global/exception/ErrorCode.java
  src/test/java/com/halfgallon/withcon/domain/performance/controller/PerformanceControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/performance/service/impl/PerformanceServiceImplTest.java
Labels: 🔨 Refactor, ✨ feature, 🔥 backend

#104 [Feat] 공연 오픈일 알림 기능 / 알림 읽음 기능 / 알림 리펙터링
  src/main/java/com/halfgallon/withcon/domain/notification/constant/Channel.java
  src/main/java/com/halfgallon/withcon/domain/notification/constant/ChatRoomGenerateType.java
  src/main/java/com/halfgallon/withcon/domain/notification/constant/NotificationMessage.java
  src/main/java/com/halfgallon/withcon/domain/notification/constant/NotificationType.java
  src/main/java/com/halfgallon/withcon/domain/notification/controller/NotificationController.java
  src/main/java/com/halfgallon/withcon/domain/notification/dto/ChatRoomNotificationRequest.java
  src/main/java/com/halfgallon/withcon/domain/notification/dto/NotificationResponse.java
  src/main/java/com/halfgallon/withcon/domain/notification/dto/RedisChannelRequest.java
  src/main/java/com/halfgallon/withcon/domain/notification/dto/VisibleRequest.java
  src/main/java/com/halfgallon/withcon/domain/notification/dto/performanceNotificationRequest.java
  src/main/java/com/halfgallon/withcon/domain/notification/dto/performanceNotificationResponse.java
  src/main/java/com/halfgallon/withcon/domain/notification/entity/Notification.java
  src/main/java/com/halfgallon/withcon/domain/notification/event/NewMessageEvent.java
  src/main/java/com/halfgallon/withcon/domain/notification/event/handler/NewMessageEventHandler.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/NotificationService.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/handler/ChatRoomRedisSubscriber.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/handler/GenerateEvent.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/handler/NotificationScheduleHandler.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/impl/NotificationServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/impl/RedisNotificationServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/performance/entitiy/PerformanceLike.java
  src/main/java/com/halfgallon/withcon/domain/performance/repository/PerformanceLikeRepository.java
  src/main/java/com/halfgallon/withcon/domain/performance/repository/PerformanceRepository.java
  src/main/java/com/halfgallon/withcon/domain/performance/service/impl/PerformanceLikeServiceImpl.java
  src/main/java/com/halfgallon/withcon/global/exception/ErrorCode.java
  src/test/java/com/halfgallon/withcon/domain/performance/service/impl/PerformanceLikeServiceImplTest.java
Labels: 🔨 Refactor, ✨ feature, 🔥 backend

#105 [refactor] 공연 검색 기능 리팩토링
  src/main/java/com/halfgallon/withcon/domain/performance/controller/PerformanceController.java
  src/main/java/com/halfgallon/withcon/domain/performance/repository/CustomPerformanceRepository.java
  src/main/java/com/halfgallon/withcon/domain/performance/repository/impl/CustomPerformanceRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/performance/service/PerformanceService.java
  src/main/java/com/halfgallon/withcon/domain/performance/service/impl/PerformanceServiceImpl.java
  src/test/java/com/halfgallon/withcon/domain/performance/controller/PerformanceControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/performance/service/impl/PerformanceServiceImplTest.java
Labels: 🔨 Refactor, 🔥 backend

#109 [Refactor] 알림 리펙터링 / 공연 찜 리펙터링
  src/main/java/com/halfgallon/withcon/domain/notification/constant/RedisCacheType.java
  src/main/java/com/halfgallon/withcon/domain/notification/constant/VisibleType.java
  src/main/java/com/halfgallon/withcon/domain/notification/controller/NotificationController.java
  src/main/java/com/halfgallon/withcon/domain/notification/dto/NotificationResponse.java
  src/main/java/com/halfgallon/withcon/domain/notification/dto/VisibleDataDto.java
  src/main/java/com/halfgallon/withcon/domain/notification/dto/VisibleRequest.java
  src/main/java/com/halfgallon/withcon/domain/notification/event/handler/NewMessageEventHandler.java
  src/main/java/com/halfgallon/withcon/domain/notification/repository/NotificationRepository.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/NotificationService.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/handler/NotificationScheduleHandler.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/impl/NotificationServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/impl/RedisNotificationServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/impl/SseEmitterServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/performance/controller/PerformanceLikeController.java
Labels: 🔨 Refactor, 🔥 backend

#110 [feat] 공연 세부 정보 기능 구현
  sql/performanceDetail.sql
  src/main/java/com/halfgallon/withcon/domain/performance/controller/PerformanceDetailController.java
  src/main/java/com/halfgallon/withcon/domain/performance/dto/request/PerformanceDetailRequest.java
  src/main/java/com/halfgallon/withcon/domain/performance/dto/response/PerformanceDetailResponse.java
  src/main/java/com/halfgallon/withcon/domain/performance/entitiy/PerformanceDetail.java
  src/main/java/com/halfgallon/withcon/domain/performance/service/PerformanceDetailService.java
  src/main/java/com/halfgallon/withcon/domain/performance/service/impl/PerformanceDetailServiceImpl.java
  src/main/java/com/halfgallon/withcon/global/exception/ErrorCode.java
  src/test/java/com/halfgallon/withcon/domain/performance/controller/PerformanceDetailControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/performance/service/impl/PerformanceDetailServiceImplTest.java
Labels: ✨ feature, 🔥 backend

#107 [feat] 엘라스틱서치 공연 아이디 추가
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/tag/controller/TagController.java
  src/main/java/com/halfgallon/withcon/domain/tag/dto/TagSearchDto.java
  src/main/java/com/halfgallon/withcon/domain/tag/entity/Tag.java
  src/main/java/com/halfgallon/withcon/domain/tag/entity/TagSearch.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/CustomTagSearchRepository.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/TagRepository.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/TagSearchRepository.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/impl/CustomTagSearchRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/tag/service/TagService.java
  src/main/java/com/halfgallon/withcon/domain/tag/service/TagServiceImpl.java
  src/main/resources/static/elastic/tag-mappings.json
  src/test/http/tag.http
Labels: ✨ feature, 🔥 backend

#111 [feat] 현재 비밀번호 확인 API 추가 및 비밀번호 재설정 기능 추가
  src/main/java/com/halfgallon/withcon/domain/auth/security/filter/ExceptionHandlingFilter.java
  src/main/java/com/halfgallon/withcon/domain/member/controller/MemberController.java
  src/main/java/com/halfgallon/withcon/domain/member/dto/request/CurrentPasswordCheckRequest.java
  src/main/java/com/halfgallon/withcon/domain/member/dto/request/UpdateMemberRequest.java
  src/main/java/com/halfgallon/withcon/domain/member/entity/Member.java
  src/main/java/com/halfgallon/withcon/domain/member/service/MemberService.java
  src/main/java/com/halfgallon/withcon/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/halfgallon/withcon/global/exception/ErrorCode.java
  src/test/java/com/halfgallon/withcon/domain/auth/service/AuthServiceImplTest.java
  src/test/java/com/halfgallon/withcon/domain/member/controller/MemberControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/member/service/impl/MemberServiceImplTest.java
Labels: ✅ Test, ✨ feature, 🔥 backend

#115 [feat] 태그 검색을 이용한 채팅방 목록 조회
  src/main/java/com/halfgallon/withcon/domain/chat/controller/ChatRoomController.java
  src/main/java/com/halfgallon/withcon/domain/chat/entity/ChatParticipant.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/ChatParticipantRepository.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/CustomChatRoomRepository.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/impl/CustomChatRoomRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/ChatRoomService.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatMessageServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/test/http/chatRoom.http
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImplTest.java
Labels: ✨ feature, 🔥 backend

#117 [refactor] 채팅 메시지 엔드포인트 변경 및 설정 추가
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatMessageRequest.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/impl/CustomChatMessageRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/test/http/chatRoom.http
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImplTest.java
Labels: ✅ Test, 🔨 Refactor, 🔥 backend

#119 [refactor] 태그 검색 시 공연 정보 조회 리팩토링
  src/main/java/com/halfgallon/withcon/domain/tag/controller/TagController.java
  src/main/java/com/halfgallon/withcon/domain/tag/dto/TagCountDto.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/CustomTagRepository.java
  src/main/java/com/halfgallon/withcon/domain/tag/repository/impl/CustomTagRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/tag/service/TagService.java
  src/main/java/com/halfgallon/withcon/domain/tag/service/TagServiceImpl.java
  src/test/http/tag.http
  src/test/java/com/halfgallon/withcon/domain/tag/repository/TagRepositoryTest.java
Labels: ✅ Test, 🔨 Refactor, 🔥 backend

#120 [Refactor] 채팅방 입장/퇴장/강퇴 알림에 대한 VIsible 조건 추가
  src/main/java/com/halfgallon/withcon/domain/notification/service/handler/NotificationScheduleHandler.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/impl/NotificationServiceImpl.java
Labels: 🔨 Refactor, 🔥 backend

#121 [refactor] 공연 조회 데이터 response 변경
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatParticipantResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomRequest.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
Labels: 🔨 Refactor, 🔥 backend

#122 [Refactor] SSE 연결시 더미 데이터 -> Json 데이터로 변경
  src/main/java/com/halfgallon/withcon/domain/notification/constant/NotificationMessage.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/handler/NotificationScheduleHandler.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/impl/NotificationServiceImpl.java
Labels: 🔨 Refactor, 🔥 backend

#124 [refactor] 채팅 response 변경
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatParticipantDto.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomEnterResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomRequest.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/entity/ChatRoom.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/CustomChatParticipantRepository.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/impl/CustomChatParticipantRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/halfgallon/withcon/global/exception/ErrorCode.java
  src/test/java/com/halfgallon/withcon/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImplTest.java
Labels: ✅ Test, 🔨 Refactor, 🔥 backend

#125 feat: 채팅 메시지 response 반환값 추가
  src/main/java/com/halfgallon/withcon/domain/chat/controller/ChatMessageController.java
  src/main/java/com/halfgallon/withcon/domain/chat/controller/ChatRoomController.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatLastMessageRequest.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/impl/CustomChatMessageRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/ChatRoomService.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatMessageServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/test/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImplTest.java
Labels: ✨ feature, 🔥 backend

#129 [feat] 채팅 접속 및 마지막 메시지 ID 저장
  src/main/java/com/halfgallon/withcon/domain/chat/config/Handler/StompPreHandler.java
  src/main/java/com/halfgallon/withcon/domain/chat/config/WebSocketConfig.java
  src/main/java/com/halfgallon/withcon/domain/chat/constant/ChattingConstant.java
  src/main/java/com/halfgallon/withcon/domain/chat/constant/EnterStatus.java
  src/main/java/com/halfgallon/withcon/domain/chat/controller/ChatParticipantController.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatLastReadMessage.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatParticipantResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomEnterResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatRoomSessionDto.java
  src/main/java/com/halfgallon/withcon/domain/chat/entity/ChatMessage.java
  src/main/java/com/halfgallon/withcon/domain/chat/entity/ChatParticipant.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/ChatParticipantRepository.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/impl/CustomChatMessageRepositoryImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/ChatParticipantService.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatParticipantServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/notification/event/handler/NewMessageEventHandler.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/RedisService.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/impl/NotificationServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/impl/RedisNotificationServiceImpl.java
  src/main/java/com/halfgallon/withcon/domain/notification/service/impl/RedisServiceImpl.java
  src/test/http/chatRoom.http
Labels: ✨ feature, 🔥 backend

#130 [bug] 채팅방 퇴장 및 강퇴 기능 버그 수정
  src/main/java/com/halfgallon/withcon/domain/chat/config/Handler/StompPreHandler.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/halfgallon/withcon/domain/chat/dto/ChatMessageResponse.java
  src/main/java/com/halfgallon/withcon/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/ChatRoomService.java
  src/main/java/com/halfgallon/withcon/domain/chat/service/impl/ChatRoomServiceImpl.java
Labels: 🐞 bug, 🔥 backend
